IWAID-13 BE - CRUD Médicos
DavidVelaz17/ConsultorioMedico pull request #1
Opened 2023-07-21 20:10 UTC by DavidVelaz17

# IWAID-13 BE - CRUD Médicos
+ In folder "entity" you can find Doctors, wich contains each doctor's params, such as id, name, specialization, address, phone_number and email, I used @Data to generate automatically setters and getters. also I used some annotations like @NotEmpty and @Email in order to secure data integrity.

+ In folder "repository" you can find DoctorRepository wich extends JpaRepository. This interface is empty because I used JpaRepository's methods such as .findById(), .save() and .deleteById() in DoctorService class.

+ In folder "services" you will find DoctorsService file, where the busyness logic is. Here I created each method to find,save, delete and update.

+ In folder "restcontrollers" you wil find DoctorController where the endpoints are created, each endpoint method uses methods from DoctorService.

- Unit Tests are not totally functioning for now, the issue is with the DoctorServiceTest, whenever I try to use doctorService.getDoctor(id) says that doctorRepository.findById(id) is null, thus I created the " IWAID-20 BE - Arreglar tests" ticket. (I tested each endpoint with postman)

2023-07-21 22:40 UTC, cgarcia-iwa requested changes
Reestructurar descripcion de PR indicando como testear y facilitar los recursos para dicha accion

2023-07-21 22:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/entity/Doctors.java
> +    private Long phone_number;
No se realizan operaciones matematicas con este dato por lo que es mejor utilizar string,

Utilizar camelCase
```suggestion
    private Long phoneNumber;
```

2023-07-21 22:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/entity/Doctors.java
> +    public Doctors() {
Revisar si con @NoArgsConstructor(access = AccessLevel.PROTECTED) se puede ahorrar este constructor

2023-07-21 22:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/entity/Doctors.java
> +    public Doctors(int id, String name, String specialization, String address,Long phone_number, String email) {
todos los parametros hacerlos final
final int id, final String name, ...etc

phone_number -> phoneNumber

2023-07-21 22:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/DoctorController.java
> +    DoctorService doctorService;
```suggestion
    private final DoctorService doctorService;
```

2023-07-21 22:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/DoctorController.java
> +    public Optional<Doctors> getDoctor(@PathVariable("doctorId") int doctorId){
```suggestion
    public Optional<Doctors> getDoctorById(@PathVariable("doctorId") final int doctorId){
```

2023-07-21 22:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/DoctorController.java
> +
borrar saltos de linea extra del comentario anterior al metodo  de la linea 30

2023-07-21 22:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/DoctorController.java
> +    public ResponseEntity delete(@PathVariable("doctorId") int doctorId){
```suggestion
    public ResponseEntity delete(@PathVariable("doctorId") final int doctorId){
```

2023-07-21 22:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/DoctorController.java
> +            return new ResponseEntity<>(HttpStatus.OK);   //Returns a ResponseEntity with the status code of 200 for OK
Prueba si puedes utilizar y cambia el tipo de retorno a ResponseEntity < Void> en el caso de ser necesario
```suggestion
            return ResponseEntity.ok().build();   //Returns a ResponseEntity with the status code of 200 for OK
```

2023-07-21 22:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/DoctorController.java
> +            return new ResponseEntity<>("Saved doctor " + doctors.getId(), HttpStatus.CREATED);  //Returns a ResponseEntity with the doctor's id and the status code of 201 for created
Prueba con ResponseEntity < Doctors > como tipo de retorno
```suggestion
            return ResponseEntity.status(HttpStatus.CREATED)
            .body( doctorService.saveDoctor(doctors));  //Returns a ResponseEntity with the doctor's id and the status code of 201 for created
```

2023-07-21 22:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +    final DoctorRepository doctorRepository;
```suggestion
    private final DoctorRepository doctorRepository;
```

2023-07-21 22:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +    public Optional<Doctors> getDoctor(int id){return doctorRepository.findById(id);}
```suggestion
    public Optional<Doctors> getDoctor(final int id){return doctorRepository.findById(id);}
```

2023-07-21 22:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +    public void saveDoctor(Doctors doctors){
Si se cambiaran los tipos de retornos en el controller, adecuar los retornos de los metodos service

2023-07-21 22:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +    public Doctors updateDoctorById(Doctors request,int id){
Replantear el tipado del return y del parametro, no se obtiene ni se regresa la entidad en los endpoint
Return -> DoctorsDTO
Parameter -> DoctorsForm

2023-07-21 22:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +        doctor.setName(request.getName());
mover toda la seccion de actualizar valores a un metodo llamado update dentro de la entidad

2023-07-21 22:53 UTC, SendyCruz requested changes

2023-07-21 22:53 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/entity/Doctors.java
> +public class Doctors {//Class name must be equal as the table name on database, if not a new table with the class name will be created
Mantener el nombre de las entidades en singular

2023-07-21 22:53 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/entity/Doctors.java
> +    //This is doctor's name, such cannot be empty, the minimum size is a name of 3 characters and the maximum is 45 characters
Consierando que es una entidad, es mejor hacerlo de la siguiente forma y de esa forma tambien evitar tantos comentarios, actualizar en todos los campos:

`  @Column(name = "name", unique = true, nullable = false, length = 150)
  private String name;`

2023-07-21 22:53 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/repository/DoctorRepository.java
> +    /*
eliminar comentario

2023-07-21 22:53 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/DoctorController.java
> +@RequestMapping(path="/iwaid/doctors")//Path where the api can be found
Eliminar comentarios, no agregan mayor contexto

2023-07-21 22:53 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +    //@Autowired
eliminar comentarios

2023-07-21 22:53 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +    public Optional<Doctors> getDoctor(int id){return doctorRepository.findById(id);}
Este metodo deberia validar dentro, si el id, que recibe, si pertenece a un doctor existente, para que el retorno sea un doctor y no un Optional<Doctors>

2023-07-21 22:53 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +    public void deleteDoctor(int id){
final int id

2023-07-21 22:53 UTC, SendyCruz commented on consultorio-medico/src/test/java/com/iwa/iwaid/consultoriomedico/restcontrollers/DoctorControllerTest.java
> +/*TODO IWAID-20
Limpiar el codigo, eliminar codigo que ya no se esta usando

2023-07-21 22:53 UTC, SendyCruz commented on consultorio-medico/src/test/java/com/iwa/iwaid/consultoriomedico/services/DoctorServiceTest.java
> +    @Test
podría quedar solo el comentario del TODO y eliminar el metodo

2023-07-21 23:00 UTC, SendyCruz requested changes

2023-07-21 23:00 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/entity/Doctors.java
> +//This is the Doctor Entity where doctor's attributes are stated
Eliminar estos comemtarios

2023-07-21 23:00 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/DoctorController.java
> +    //The path to update a doctor's info is /{id}, the {id} must be replaced by an actual doctor's id
eliminar comentarios

2023-07-21 23:00 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/entity/Doctors.java
> +    //This is the doctor's ID, we use @Id to specify it and @NotNull to throw and exception if so
```suggestion
```

2023-07-21 23:00 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/DoctorController.java
> +    public ResponseEntity updateById(@RequestBody Doctors doctors, @PathVariable("doctorId")int doctorId){
doctor, solo se editar un doctor

2023-07-21 23:00 UTC, SendyCruz commented on consultorio-medico/src/test/java/com/iwa/iwaid/consultoriomedico/ConsultorioMedicoApplicationTests.java
> -class ConsultorioMedicoApplicationTests {
Evitar español dentro del código

2023-07-21 23:05 UTC, SendyCruz requested changes

2023-07-21 23:05 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/DoctorController.java
> +import org.springframework.web.bind.annotation.*;
evitar los * en los import

2023-07-21 23:05 UTC, SendyCruz commented on consultorio-medico/src/test/java/com/iwa/iwaid/consultoriomedico/services/DoctorServiceTest.java
> +    @Test
no colocar los metodos si estaran vacios, se trabaran en otro ticket?

2023-07-21 23:05 UTC, SendyCruz commented
Agregar evidencia en el PR

2023-07-21 23:07 UTC, SendyCruz requested changes

2023-07-21 23:07 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/entity/Doctors.java
> +import jakarta.validation.constraints.*;
evitar *

2023-07-21 23:07 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/entity/Doctors.java
> +import jakarta.validation.constraints.*;
evitar *

2023-07-21 23:08 UTC, SendyCruz commented
En general, limpiar el código para una mejor legibilidad, eliminar comentarios dentro de las clases y solo mantener los de tipo TODO

2023-07-22 02:46 UTC, DavidVelaz17 commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/entity/Doctors.java
> +    //This is doctor's name, such cannot be empty, the minimum size is a name of 3 characters and the maximum is 45 characters
Reemplazo la anotación de @NotEmpty por @Column o dejo las tres en cada campo?

2023-07-25 00:00 UTC, cgarcia-iwa requested changes

2023-07-25 00:00 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/dto/DoctorDTO.java
> +    @ApiObjectField(name="phoneNumber",description = "Doctor's phoneNumber")
```suggestion
    @ApiObjectField(name="phoneNumber",description = "Doctor's phone number")
```

2023-07-25 00:00 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/form/DoctorForm.java
> +    @ApiObjectField(name="id",description = "Doctor's id")
los simbolos '=' deben deben de estar separados por espacios para mayor legibilidad
```suggestion
    @ApiObjectField(name = "id", description = "Doctor's id")
```
Replicar en los casos que se repita esta situacion

2023-07-25 00:00 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/DoctorController.java
> +            return ResponseEntity.notFound().build();
```suggestion
            return ResponseEntity.ok().build();
```

2023-07-25 00:00 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/DoctorController.java
> +        DoctorDTO doctorDTO=doctorService.getDoctor(doctorId);
```suggestion
        DoctorDTO doctorDTO = doctorService.getDoctor(doctorId);
```

2023-07-25 00:00 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/DoctorController.java
> +        if (doctorDTO!=null && form!=null) {
toda validacion va en el service, si quieres validar aqui debes llamar a un metodo del service que realice esta accion

2023-07-25 00:00 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/DoctorController.java
> +            return ResponseEntity.notFound().build();
En el update es mejor regresar un Exception que termine con todo el proceso

2023-07-25 00:00 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +        if(doctorRepository.findById(id).isPresent()) {
En vez de replicar el findById 2 veces en la linea 17 y 18, crea un metodo en el repository validateIfDoctorExist que regrese un booleano buscando por Id

2023-07-25 00:00 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +            return null;
Una vez implementado el validateIfExist retornar un error en vez del null en caso de que no encuentre y mover todo esto a un metodo independiente

2023-07-25 01:57 UTC, cgarcia-iwa requested changes

2023-07-25 01:57 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/form/DoctorForm.java
> +    private int id;
la ID no la recibes en el form, en su lugar recibela en el path del post ya que el create debe generarla automaticamente

2023-07-25 18:01 UTC, cgarcia-iwa approved these changes

2023-07-25 18:01 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/DoctorController.java
> +        return new ResponseEntity<>("Saved doctor " + doctorDTO.getId(), HttpStatus.CREATED);
return ResponseEntity.status(HttpStatus.CREATED).body(doctorService.saveDoctor(form));

Prueba con ese

2023-07-25 18:01 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +    private boolean validateIfDoctorExists(int id) throws Exception {
con la excepcion ya no necesitas retornar el true, cambia a void y que el error detenga el proceso

2023-07-26 19:42 UTC, cgarcia-iwa approved these changes

2023-07-26 20:16 UTC, SendyCruz requested changes

2023-07-26 20:16 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/entity/Doctor.java
> +import jakarta.persistence.*;
evitar *

2023-07-26 20:16 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/entity/Doctor.java
> +@Data
podrías revisar si es suficiente con @Getter

2023-07-26 20:16 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +    public DoctorDTO getDoctor(final int id) throws Exception {
getDoctorById

2023-07-26 20:16 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +    public DoctorDTO saveDoctor(final DoctorForm form) {
createDoctor

2023-07-26 20:16 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +    public DoctorDTO updateDoctorById(final DoctorForm form, final int id) throws Exception {
UpdateDoctor

2023-07-26 20:16 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +        validateIfDoctorExists(id);
podrias mandar a llamar a getDoctorById de este mismo service

2023-07-26 20:16 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +            throw new Exception("Doctor no found");
Doctor not found

2023-07-28 23:00 UTC, cgarcia-iwa approved these changes

2023-07-28 23:00 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/config/ApplicationConfig.java
> +                .allowedOrigins("3000")
revisar si el 3000 sigue siendo correcto

2023-07-28 23:00 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/config/ApplicationConfig.java
> +        registry.addMapping("/iwaid/doctors")
falta el allowHeaders

2023-07-30 18:19 UTC, merged