IWAID-6 BE - CRUD Citas Médicas
DavidVelaz17/ConsultorioMedico pull request #11
Opened 2023-08-04 05:10 UTC by DavidVelaz17

### Ticket:
* [IWAID-6](https://iwaids.atlassian.net/browse/IWAID-6?atlOrigin=eyJpIjoiYjAzYjcwZjhhMjIwNDY5NDk3ODZjZWJiOWEwMzNiZDUiLCJwIjoiaiJ9)

### What Changed:
* Changed server port from 8080 to 8081
* New RESTful endpoint for handling medical appointments

### How To Test:
*  To test each endpoint you need to excecute the project and then go to Postman.
    * To get All appointments, create a new GET request with the following route: http://localhost:8081/iwaid/appointments/
    * To get a specific appointment, create a new GET request with the following route: http://localhost:8081/iwaid/appointments/{id}
    * To create an appointment then create a POST request with the following route:http://localhost:8081/iwaid/appointments/ 
       * Go to "Body " section and select "raw", then in "text" select "JSON" and pase the following:
          * {
    "patientId":"1",
    "doctorId":"2",
    "date":"2023-11-02",
    "hour":"FIVE_PM",
    "notes":"Patient need to arrive seven minutes earlier"
}
    * To delete an appointment, create a DELETE request with the following route: http://localhost:8081/iwaid/appointments/{id}
    * To update an appointment, crete a PATCH request with the following route: http://localhost:8081/iwaid/appointments/{id}
        * Go to "Body " section and select "raw", then in "text" select "JSON" and pase the following:
             *  {
    "patientId":"1",
    "doctorId":"1",
    "date":"2024-11-02",
    "hour":"TRHEE_PM",
    "notes":"Patient need to arrive five minutes earlier"
}
        > If the route has an {id} then you must change it for a number, ex: http://localhost:8081/iwaid/appointments/2

### Evicence: 
* Get All Appointments:
![findAll](https://github.com/DavidVelaz17/iwaid-api/assets/139006505/ce0bb3e3-e38a-4b5b-aad0-19a24b7bc174)
* Fin Appointment By Id:
![FindById](https://github.com/DavidVelaz17/iwaid-api/assets/139006505/d4e2db5c-1c67-4ea5-b1b8-c085c36f4ee6)
* Create an Appointment:
![create](https://github.com/DavidVelaz17/iwaid-api/assets/139006505/fc068808-5746-446f-8169-b2d52736655e)
* Delete Appointment By Id:
![delete](https://github.com/DavidVelaz17/iwaid-api/assets/139006505/199cb009-c747-47d7-a2c6-97b1a44d2909)
* Update Appointment By Id:
![update](https://github.com/DavidVelaz17/iwaid-api/assets/139006505/00f1eeba-5193-458e-af7d-8031897176ed)

2023-08-04 16:30 UTC, SendyCruz requested changes

2023-08-04 16:30 UTC, SendyCruz commented on consultorio-medico/target/classes/com/iwa/iwaid/consultoriomedico/dto/AppointmentDTO$AppointmentDTOBuilder.class
no cargar estos archivos

2023-08-04 16:30 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/AppointmentController.java
> +    public ResponseEntity saveAppointment(@RequestBody @Valid AppointmentForm form) throws Exception {
```suggestion
    public ResponseEntity createAppointment(@RequestBody @Valid AppointmentForm form) throws Exception {
```

2023-08-04 16:30 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/AppointmentService.java
> +    public AppointmentDTO saveAppointment(final AppointmentForm form) throws Exception {
```suggestion
    public AppointmentDTO createAppointment(final AppointmentForm form) throws Exception {
```

2023-08-04 16:30 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/form/AppointmentForm.java
> +    @ApiObjectField(name = "hour", description = "Appointment's hour")
@NotNull

2023-08-04 16:32 UTC, SendyCruz commented
Duda: como se va a controlar, que ya no se pueda agendar una cita en la misma fecha y hora?

2023-08-04 16:40 UTC, cgarcia-iwa requested changes
Subiste los archivos de target, quitalos y agrega la carpeta a la exepcion

2023-08-04 16:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/convertors/HourToIntConvertor.java
> +public class HourToIntConvertor implements AttributeConverter<Hour,Integer> {
```suggestion
public class HourConvertor implements AttributeConverter<Hour,Integer> {
```

2023-08-04 16:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/entity/Appointment.java
> +    private LocalDate date;
que vas a guardar, dependiendo la respuesta verificar si es correcto el tipo LocalDate o Date

2023-08-04 16:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/AppointmentController.java
> +    @GetMapping("/")
```suggestion
    @GetMapping
```

2023-08-04 16:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/AppointmentController.java
> +        return appointments;
```suggestion
        return appointmentService.getAll();
```

2023-08-04 16:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/AppointmentController.java
> +    @PostMapping("/")
```suggestion
    @PostMapping
```

2023-08-04 16:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/AppointmentController.java
> +    public ResponseEntity<AppointmentDTO> deleteAppointment(@PathVariable("appointmentId") final int appointmentId) throws Exception {
```suggestion
    public ResponseEntity<Void> deleteAppointment(@PathVariable("appointmentId") final int appointmentId) throws Exception {
```

2023-08-04 16:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/AppointmentService.java
> +        return appointments.stream().map(appointment -> AppointmentDTO.build(appointment, doctorDTOMap.get(appointment.getDoctorId()), patientDTOMap.get(appointment.getPatientId()))).toList();
dale un formato de cascada

2023-08-04 16:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/AppointmentService.java
> +        return doctorDTOMap;
```suggestion
        return doctorService.getDoctorsByIds(doctorsIds);
```

2023-08-04 16:40 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +        final List<DoctorDTO> doctorDTOs = doctors.stream().map(DoctorDTO::build).toList();
mueve la linea 54 y 53 a un metodo privado que funcione igual que el findAll y lo mandas a traer aqui

2023-08-04 18:39 UTC, cgarcia-iwa requested changes

2023-08-04 18:39 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/dto/AppointmentDTO.java
> +    @ApiObjectField(name = "patient", description = "Patient's data")
el nombre de la variable ya no coincide con el api object

2023-08-04 18:39 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/dto/AppointmentDTO.java
> +    @ApiObjectField(name = "doctor", description = "Doctor's data")
ditto

2023-08-04 18:39 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/AppointmentController.java
> +                                                                @PathVariable("appointmentId") final int appointmentId)
cooregir a formato cascada mas adecuado

2023-08-06 22:22 UTC, cgarcia-iwa requested changes

2023-08-06 22:22 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
>              throw new Exception("Doctor not found");
Todos los errores guardarlo en un archivos de constantes, para evitar que el usar el mismo error en otras secciones pueda variar

2023-08-07 03:02 UTC, cgarcia-iwa approved these changes

2023-08-07 17:05 UTC, SendyCruz requested changes

2023-08-07 17:05 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/AppointmentService.java
> +    public AppointmentDTO getAppointmentById(final int id) throws Exception {
```suggestion
    public AppointmentDTO getAppointmentById(final int appointmentId) throws Exception {
```

2023-08-07 17:05 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/AppointmentService.java
> +    public void deleteAppointment(final int id) throws Exception {
```suggestion
    public void deleteAppointment(final int appointmentId) throws Exception {
```

2023-08-07 17:05 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/AppointmentService.java
> +    private void validateIfAppointmentExists(final int id) throws Exception {
```suggestion
    private void validateIfAppointmentExists(final int appointmentId) throws Exception {
```

2023-08-07 17:05 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/AppointmentService.java
> +    private void validateDoctorAndDateAndHour(
```suggestion
    private void validateDoctorAvailability(
```

2023-08-07 17:05 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/AppointmentService.java
> +    private void validatePatientAndDateAndHour(
```suggestion
    private void validatePatientAvailability(
```

2023-08-07 17:05 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +    public void validateIfDoctorExists(final int id) throws Exception {
```suggestion
    public void validateIfDoctorExists(final int doctorId) throws Exception {
```

2023-08-07 17:05 UTC, SendyCruz commented on consultorio-medico/src/main/resources/ValidationMessages.properties
> +positive.tel.number=Please insert a real telephone number
```suggestion
positive.tel.number= Enter a valid phone number.
```

2023-08-07 17:05 UTC, SendyCruz commented on consultorio-medico/src/main/resources/ValidationMessages.properties
> +not.found=The requested data does not exist yet
```suggestion
not.found=The requested data does not exist yet.
```

2023-08-07 17:05 UTC, SendyCruz commented on consultorio-medico/src/main/resources/ValidationMessages.properties
> +date.and.hour.available=The selected date and hour were available
es que no estaban disponibles?

2023-08-07 17:39 UTC, DavidVelaz17 commented on consultorio-medico/src/main/resources/ValidationMessages.properties
> +date.and.hour.available=The selected date and hour were available
No, es solo para decir que si se realizó la acción

2023-08-08 16:43 UTC, cgarcia-iwa requested changes

2023-08-08 16:43 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/MedicineController.java
> +@RequestMapping(path = "/iwaid/medicines/")
determinar con el resto del equipo el estandar que utilizaran para las rutas

2023-08-08 16:43 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/AppointmentService.java
> +        if(appointmentRepository.existsByDoctorIdAndPatientIdAndDateAndHour(doctorId,patientId,date,hour)){
Que pasa si solo actualizo las notas, me dejara actualizar o fallara?

2023-08-08 22:29 UTC, cgarcia-iwa approved these changes

2023-08-08 23:14 UTC, merged