Iwaid 8 crud prescripciones
DavidVelaz17/ConsultorioMedico pull request #12
Opened 2023-08-06 04:25 UTC by IrvingF-4

**Ticket:**

- [IWAID-8](https://iwaids.atlassian.net/browse/IWAID-8)

**Overview:**
The endpoint for managing medical prescriptions has been implemented. And also, the file for creating the table of medical prescriptions has been added.

**What a change:**
The endpoint for handling medical histories has been developed, which allows retrieving all of them, a specific one by ID, updating, and deleting.

**How to test:**
To test the endpoint, it is necessary to run the project and open Postman.

- To test by fetching all the registered prescriptions, you need to create a new GET request with the following URL: http://localhost:8080/iwaid/prescription, and send the request, which will return a JSON with all the created prescriptions and a status of 200.
- To retrieve a specific prescription, you need to create a GET request with the following URL: [http://localhost:8080/iwaid/prescription/{id}](http://localhost:8080/iwaid/prescription/%7Bid%7D), where id is replaced with the desired prescription's ID. When you send the request, it will return all the data of the prescription, if it's found, with a status of 200.
- To save a new prescription, you need to create a new POST request with the following URL: http://localhost:8080/iwaid/prescription and include a JSON in the request body like the following:                                                          
{
    "patientId": 1,
    "doctorId": 1,
    "date": "2023-08-05",
    "description": ""
}                                                                                                                                                                                                   
 If there are no issues with the data saved when you send the request, it will return a JSON with the prescription data and a status of 201.

- To update a prescription, you need to create a new PATCH request with the following URL: [http://localhost:8080/iwaid/prescription/{id}](http://localhost:8080/iwaid/prescription/%7Bid%7D), where {id} is the ID of the prescription you want to update. Include a JSON in the request body as follows:                                                                           
 {
    "patientId": 3,
    "doctorId": 1,
    "date": "2023-08-05",
    "description": "Data to be changed"
}                                                                                                                                                                                                         
 By sending the request, it will update the prescription with the provided data, and if there are no issues, it will return a JSON with the updated prescription data and a status of 200.

- To delete a prescription, you need to create a new DELETE request with the following URL: [http://localhost:8080/iwaid/prescription/{id}](http://localhost:8080/iwaid/prescription/%7Bid%7D), where {id} is the ID of the prescription you want to delete. If everything goes well, it will send a status of 200.

**Evidence:**
- Get all prescriptions:
 
 ![image](https://github.com/DavidVelaz17/iwaid-api/assets/85428204/0ceae266-bdd1-4e82-8efb-80bbac3a078e)

- Search Prescription by ID:
 
 ![image](https://github.com/DavidVelaz17/iwaid-api/assets/85428204/c1b48a3b-3340-4656-998a-60c460474201)

- Create a new prescription:
 
![image](https://github.com/DavidVelaz17/iwaid-api/assets/85428204/d8e09d88-31fe-4164-8fab-061a36ae8f09)

- Update a prescription:
 
![image](https://github.com/DavidVelaz17/iwaid-api/assets/85428204/4d5ac4d2-e96f-4f6f-bdb1-f4be716e1f06)

- Delete a prescription

![image](https://github.com/DavidVelaz17/iwaid-api/assets/85428204/0e99fe0f-9ed4-4194-964e-ce690fe5d7ae)

- Creation of the prescription file for flyway:
![image](https://github.com/DavidVelaz17/iwaid-api/assets/85428204/cef7c146-512b-4ee5-9a57-0cc3f6559cc3)

2023-08-07 16:15 UTC, SendyCruz approved these changes

2023-08-07 16:15 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/dto/PrescriptionDTO.java
> +    private LocalDate date;
esta fecha indica la fecha de registro? entonces su nombre correcto sería registerDate

2023-08-07 16:15 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/dto/PrescriptionDTO.java
> +    @ApiObjectField(name = "date", description = "Prescription date")
actualiza descripción

2023-08-07 16:15 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/dto/PrescriptionDTO.java
> +    @ApiObjectField(name = "description", description = "Prescription description")
```suggestion
    @ApiObjectField(name = "description", description = "Prescription's description")
```

2023-08-07 16:15 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/PrescriptionController.java
> +    @GetMapping("/{id}")
id de que? renombrar

2023-08-07 16:15 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/PrescriptionController.java
> +                                                              @PathVariable final int id) throws Exception {
ditto

2023-08-07 16:15 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/PrescriptionController.java
> +    public ResponseEntity<Void> deletePrescription(@PathVariable final int id) throws Exception {
ditto

2023-08-07 16:15 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/PrescriptionService.java
> +    public PrescriptionDTO findPrescriptionById(final int id) throws Exception {
prescriptionId

2023-08-07 16:15 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/PrescriptionService.java
> +    public PrescriptionDTO updatePrescription(final PrescriptionForm form, final int id)
prescriptionId

2023-08-07 16:15 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/PrescriptionService.java
> +    public void deletePrescription(final int id) throws Exception {
prescriptionId

2023-08-07 16:15 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/PrescriptionService.java
> +    public void validateIfPrescriptionExist(final int id) throws Exception {
prescriptionId

2023-08-07 16:15 UTC, SendyCruz commented on consultorio-medico/src/main/resources/db/migration/V1_005__Prescriptions.sql
> +    `patients_id` INT NOT NULL,
```suggestion
    `patient_id` INT NOT NULL,
```

2023-08-07 16:15 UTC, SendyCruz commented on consultorio-medico/src/main/resources/db/migration/V1_005__Prescriptions.sql
> +    `doctors_id` INT NOT NULL,
```suggestion
    `doctor_id` INT NOT NULL,
```

2023-08-07 16:17 UTC, SendyCruz requested changes

2023-08-07 16:17 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/DoctorService.java
> +    public void validateIfDoctorExists(int id) throws Exception {
doctorId

2023-08-07 16:17 UTC, SendyCruz commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/PatientService.java
>      public void validateIfPatientExist(final int id) throws Exception {
patientId

2023-08-08 16:31 UTC, cgarcia-iwa requested changes

2023-08-08 16:31 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/restcontrollers/PrescriptionController.java
> +@RequestMapping(path = "/iwaid/prescription")
definan un estandar de las rutas del back, unas estan terminando con / y otras no

2023-08-08 16:31 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/PrescriptionService.java
> +        final Prescription prescription = new Prescription(form);
moverlo despues de las validaciones, replicar en casos similares

2023-08-08 16:31 UTC, cgarcia-iwa commented on consultorio-medico/src/main/java/com/iwa/iwaid/consultoriomedico/services/PrescriptionService.java
> +            throw new Exception("Prescription not found with ID: " + prescriptionId);
determinar estandar para los errores

2023-08-09 17:01 UTC, SendyCruz commented
resolver conflictos

2023-08-09 18:53 UTC, SendyCruz approved these changes

2023-08-09 20:40 UTC, cgarcia-iwa approved these changes

2023-08-09 20:56 UTC, merged